import { Badge } from "@/components/ui/badge";
import { Download, FileText, Calendar as CalendarIcon, Printer, Play, Plus, ChevronLeft } from "lucide-react";
import { format } from "date-fns";
import { useState } from "react";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import { useLocation } from "wouter";
import { useMutation, useQueryClient, useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { api } from "@shared/routes";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";

export default function Reports() {
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [selectedReportDate, setSelectedReportDate] = useState<string | null>(null);
  const [dateForNewReport, setDateForNewReport] = useState<Date>(new Date());

  const { data: reports, isLoading: reportsLoading } = useQuery({
    queryKey: ["/api/eligibility-reports"],
  });

  const { data: reportData, isLoading: detailsLoading } = useQuery({
    queryKey: [api.reports.eligibility.path, { date: selectedReportDate }],
    enabled: !!selectedReportDate,
  });

  const createReportMutation = useMutation({
    mutationFn: async (date: string) => {
      const res = await apiRequest("POST", "/api/eligibility-reports", { date });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/eligibility-reports"] });
      toast({ title: "Success", description: "Eligibility list created" });
    },
    onError: (err: any) => {
      toast({ variant: "destructive", title: "Error", description: err.message });
    }
  });

  const generateTicketsMutation = useMutation({
    mutationFn: async (date: string) => {
      const res = await apiRequest("POST", api.tickets.generate.path, { date });
      return res.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: [api.tickets.list.path] });
      queryClient.invalidateQueries({ queryKey: [api.reports.eligibility.path] });
      toast({ title: "Success", description: data.message });
    },
  });

  const handleExport = (date: string) => {
    window.open(`${api.reports.export.path}?date=${date}`, '_blank');
  };

  const handlePrint = (date: string) => {
    setLocation(`/tickets/print?date=${date}`);
  };

  if (!selectedReportDate) {
    return (
      <div className="p-8 space-y-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Eligibility Reports</h1>
            <p className="text-muted-foreground">Manage daily eligibility lists and tickets.</p>
          </div>
          <div className="flex items-center gap-4">
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" className="gap-2">
                  <Plus className="h-4 w-4" />
                  New Eligibility List
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-4 space-y-4" align="end">
                <Calendar
                  mode="single"
                  selected={dateForNewReport}
                  onSelect={(d) => d && setDateForNewReport(d)}
                />
                <Button 
                  className="w-full" 
                  onClick={() => createReportMutation.mutate(format(dateForNewReport, "yyyy-MM-dd"))}
                  disabled={createReportMutation.isPending}
                >
                  Create for {format(dateForNewReport, "PP")}
                </Button>
              </PopoverContent>
            </Popover>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {reportsLoading ? (
             <div className="col-span-full py-12 text-center">Loading reports...</div>
          ) : reports?.map((report: any) => (
            <Card key={report.id} className="hover-elevate cursor-pointer" onClick={() => setSelectedReportDate(report.date)}>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Report for {format(new Date(report.date), "PPP")}</CardTitle>
                <FileText className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold capitalize">{report.status}</div>
                <p className="text-xs text-muted-foreground">Generated by {report.generatedBy}</p>
                <div className="mt-4 flex gap-2">
                  <Button variant="outline" size="sm" onClick={(e) => { e.stopPropagation(); handlePrint(report.date); }}>Tickets</Button>
                  <Button variant="outline" size="sm" onClick={(e) => { e.stopPropagation(); handleExport(report.date); }}>Export</Button>
                </div>
              </CardContent>
            </Card>
          ))}
          {!reportsLoading && reports?.length === 0 && (
            <div className="col-span-full py-12 text-center border-2 border-dashed rounded-lg">
              <p className="text-muted-foreground">No reports generated yet. Click "New Eligibility List" to start.</p>
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-8">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={() => setSelectedReportDate(null)}>
            <ChevronLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Report: {format(new Date(selectedReportDate), "PPP")}</h1>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <Button 
            variant="outline" 
            onClick={() => generateTicketsMutation.mutate(selectedReportDate)}
            disabled={generateTicketsMutation.isPending}
            className="gap-2"
          >
            <Play className="h-4 w-4" />
            Generate Tickets
          </Button>
          <Button variant="outline" onClick={() => handlePrint(selectedReportDate)} className="gap-2">
            <Printer className="h-4 w-4" />
            Print Tickets
          </Button>
          <Button onClick={() => handleExport(selectedReportDate)} className="gap-2">
            <Download className="h-4 w-4" />
            Export CSV
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Student Eligibility Detail
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Student ID</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Grade/Class</TableHead>
                <TableHead>Plan</TableHead>
                <TableHead>Meals Left</TableHead>
                <TableHead>Daily Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {detailsLoading ? (
                <TableRow><TableCell colSpan={6} className="text-center">Loading details...</TableCell></TableRow>
              ) : reportData?.map((item: any) => (
                <TableRow key={item.studentId}>
                  <TableCell className="font-medium">{item.studentId}</TableCell>
                  <TableCell>{item.name}</TableCell>
                  <TableCell>{item.grade} - {item.class}</TableCell>
                  <TableCell className="capitalize">{item.planType}</TableCell>
                  <TableCell>{item.mealsRemaining}</TableCell>
                  <TableCell>
                    {item.usedToday ? (
                      <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                        Used {item.usedAt && `(${format(new Date(item.usedAt), "HH:mm")})`}
                      </Badge>
                    ) : (
                      <Badge variant="outline" className="text-muted-foreground">
                        Pending
                      </Badge>
                    )}
                  </TableCell>
                </TableRow>
              ))}
              {(!reportData || reportData.length === 0) && !detailsLoading && (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">
                    No student data found for this report.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
